#!/usr/bin/env bash

export EDITOR=nvim
export ROOTEDITOR=doasedit
export PAGER=less
export TERM=wezterm
export BROWSER=qutebrowser
export TBROESER=elinks
export FILEM=vifm
export WEECHAT_HOME=~/.weechat

# Golang
export GOPATH=~/go/src
