#!/bin/bash

video_open (){
	INMEDIADIR=false
	pwd | grep Media > /dev/null && INMEDIADIR=true 

	if [ $INMEDIADIR = true ]; then
		RES1080=false
		RES720=false
		RES480=false
		MEDIAINFO=$(mediainfo $1)

		echo $MEDIAINFO | grep 1080 > /dev/null && RES1080=true
		echo $MEDIAINFO | grep 720 > /dev/null && RES720=true
		echo $MEDIAINFO | grep 480 > /dev/null && RES480=true
		if [ $RES1080 = true ]; then
			devour mpv --fs --glsl-shaders="~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl:~~/shaders/Anime4K_DarkLines_HQ.glsl:~~/shaders/Anime4K_ThinLines_HQ.glsl:~~/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl" $1
		elif [ $RES480 = true || $RES720=true ]; then
			devour mpv --fs --glsl-shaders="~~/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl:~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl:~~/shaders/Anime4K_DarkLines_HQ.glsl:~~/shaders/Anime4K_ThinLines_HQ.glsl:~~/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl" $1
		fi
	else
		devour mpv --fs $1
	fi
}

o () {
	if [ -f $1 ] ; then # Test to see if $1 if a file or not.
		case $(echo $1 | awk '{print tolower($0)}') in # If $1 if a file it opens if dependent on the file extinction. 
			*.org)   emacsgui 	$1& ;;      
			#*.mkv)   video_open 	$1	;;      
			#*.mp4)   video_open	$1 	;;      
			#*.webm)  video_open	$1 	;;      
			#*.avi)   video_open	$1 	;;      
			#*.mov)   video_open	$1 	;;      
			*.mkv)  mpv --fs 	$1	;;      
			*.mp4)  mpv --fs	$1 	;;      
			*.webm) mpv --fs	$1 	;;      
			*.avi)  mpv --fs	$1 	;;      
			*.mov)  mpv --fs	$1 	;;      
			*.m4b)   mpv		$1 	;;      
			*.m4a)   mpv		$1 	;;      
			*.mp3)   mpv	 	$1  ;;      
			*.ogg)   mpv	 	$1  ;;      
			*.flac)  mpv	 	$1  ;;      
			*.pdf)   zathura	$1& ;;      
			*.ps)    zathura	$1& ;;      
			#*.cbz)   qcomicbook	$1& ;;      
			*.cbz)   zathura	$1& ;;      
			*.cbr)   zathura	$1& ;;      
			*.epub)  zathura	$1& ;;      
			*.html)  devour badwolf		$1& ;;      
			*.png)	 devour feh		$1&	;;
			*.jpg)	 devour feh		$1&	;;
			*.webp)	 devour feh		$1&	;;
			*.gif)	 devour feh		$1&	;;
			*.sc)	 sc-im		$1	;;
			*.csv)	 sc-im		$1	;;
			*.tsv)	 sc-im		$1	;;
			*.ods)	 sc-im		$1	;;
			*)       $EDITOR 	$1	;;
		esac
	# If it is not a file then it tests to see if it's a dir and if so it opens it with the file manager. 
	elif [ -d $1 ];then 
		#$FILEM $1 # Uncomment if not useing my zshrc.
		f $1 # Comment if not useing my zshrc.
	else # If it in nether a File or Dir if will just open it in vim. 
		$EDITOR $1
	fi
}
