#!/usr/bin/env zsh

#Package Manager alias

# Void Linux
alias xin="doas xbps-install"
alias xup="doas xbps-install -S -u"
alias xrm="doas xbps-remove"
alias xro="doas xbps-remove -o"
alias xqu="xbps-query -s"

# Arch Linux
PARUIN=false
alias pkeys="doas pacman -Sy archlinux-keyring"; alias pkey="pkeys"
paru --version 2> /dev/null > /dev/null && {
	alias pin="paru -S"
	alias pup="paru -Syu"
	alias prm="paru -Rs"
	alias pro="paru -Qtdq | paru -Rns -"
	alias pqu="paru -Ss"
	PARUIN=true
}
if [ $PARUIN = false ]; then
	alias pin="doas pacman -S"
	alias pup="doas pacman -Syu"
	alias prm="doas pacman -Rs"
	alias pro="doas pacman -Qtdq | doas pacman -Rns -"
	alias pqu="pacman -Ss"
fi

# Debian
APT=apt
which aptitude 2> /dev/null > /dev/null && APT=aptitude
which nala 2> /dev/null > /dev/null && APT=nala

if [ $APT = "nala" ]; then
	alias ain="doas nala install"
	alias aup="doas nala upgrade"
	alias aupd="doas nala update"
	alias arm="doas nala remove"
	alias aro="doas nala autoremove"
	alias aqu="nala search"
	alias afe="doas nala fetch --debian testing --auto"
	alias apt="nala"
elif [ $APT = "aptitude" ]; then
	alias ain="doas aptitude install"
	alias aup="doas aptitude update && doas aptitude safe-upgrade"
	alias aupd="doas aptitude update"
	alias aupg="doas aptitude full-upgrade"
	alias arm="doas aptitude remove"
	alias aro="doas apt autoremove"
	alias aqu="aptitude search"
	alias apt="aptitude"
else
	alias ain="doas apt install"
	alias aup="doas apt update && doas apt upgrade"
	alias aupd="doas apt update"
	alias aupg="doas apt upgrade"
	alias arm="doas apt remove"
	alias aro="doas apt autoremove"
	alias aqu="apt search"
fi
alias ap="apt-file find"
alias apu="apt-file update"
alias ali="dpkg -L"

# Gentoo
alias e="doas emerge --autounmask"
alias ein="doas emerge --autounmask -va"
alias erm="doas emerge --autounmask -va --unmerge"
alias ero="doas emerge --autounmask -va --depclean"
alias eup="doas emerge --autounmask -auvDU @world"
alias eupd="doas emaint --auto sync"
alias etcup="doas etc-update"
which eix 2> /dev/null > /dev/null && {;
	alias equ="eix"
	alias eqr="eix -R"
  alias eupd="doas eix-sync"
}

# Bedrock linux
alias pmqu="pmm-query -R -s"
if [ $PARUIN = false ]; then
	alias pmup="doas pmm-install -S -u"
else
	alias pmup="doas pmm-install -S -u && paru -Syu"
fi

# Nxi
alias ns="nix search nixpkgs"
