#!/bin/zsh

neofetch

# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$fg[yellow]%}🍌%b "

# Pretty-print man pages.
export LESS_TERMCAP_mb=$'\E[1;35m' # Magenta
export LESS_TERMCAP_md=$'\E[1;35m' # Magenta
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_so=$'\E[1;33m' # Yellow
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_us=$'\E[1;36m' # Cyan

# Functions to change the default settings.
editor () {; export EDITOR=$* && echo "The editor is set to $EDITOR" && fileOpenAlias;} 
pager () {; export PAGER=$* && echo "The pager is set to $PAGER"; } 
browser () {; export BROWSER=$* && echo "The browser is set to $BROWSER"; } 
tbrowser () {; export TBROESER=$* && echo "The terminal browser is set to $TBROESER"; } 
filem () {; export FILEM=$* && echo "The file manager is set to $FILEM" && setfileman; }

#Lynx
duck () {; lynx "duckduckgo.com/lite?kd=-1&kp=-1&q=$*"; }
alias '?'="duck"

# File/Dir opeing 
fileOpenAlias () {
    alias nba="$EDITOR ~/.config/newsboat/urls"
    alias tconf="$EDITOR ~/.tmux.conf"
	alias emrc="$EDITOR ~/.emacs.d/init.el"
	sp () {; $EDITOR $(mktemp --suffix=.md) ;}
}
fileOpenAlias
confing_dir_edit () {
    if [[ $2 != "" ]]; then; cd $1; fi
    CDE_FILE=$(find $1/* -type f | fzf --height=10 --reverse)
    if [[ $CDE_FILE = "" ]]; then; f $1; else; o $CDE_FILE; fi
}
alias zrc="confing_dir_edit $ZSOURCE"
alias vrc="confing_dir_edit ~/.config/nvim cd" 
alias vfmc="confing_dir_edit ~/.config/vifm"
alias pe="confing_dir_edit /etc/portage"

# Tuir (Trminal Reddit)
export TUIR_EDITOR=$EDITOR
export TUIR_BROWSER=$BROWSER
alias tuir="tuir --enable-media"
alias reddit="tuir --enable-media"
# Edit commandline in $EDITOR
zstyle :zle:edit-command-line editor $EDITOR -f
bindkey -M vicmd v edit-command-line

# Plugins
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^ ' autosuggest-accept

source /home/mip/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

alias luamake=/home/mip/gitStuffs/lua-language-server/3rd/luamake/luamake

autoload -Uz compinit
fpath+=~/.zfunc
