#!/usr/bin/env bash

[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "marlonrichert/zsh-autocomplete"
plug "hlissner/zsh-autopair"
plug "ianthehenry/zsh-autoquoter"

# plug "jeffreytse/zsh-vi-mode"
