#!/usr/bin/env bash

PATH="$PATH:$HOME/.config/herbstluftwm"
source $HOME/.config/herbstluftwm/hc
dynamicBorderWidth.sh &

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
MOD=Mod4	#Use the super key as the main modifier
TERM=alacritty	# Set my preferred terminal

hc keybind $MOD-Shift-q reload
hc keybind $MOD-g close_or_remove

# Application Launch Keybindings
hc keybind $MOD-Return spawn $TERM
hc keybind $MOD-p spawn dmenu_run
hc keybind $MOD-Control-p spawn p
hc keybind $MOD-b spawn nobar
hc keybind $MOD-i spawn imagecopy
hc keybind $MOD-t spawn qutebrowser
hc keybind $MOD-c spawn OFpicom
hc keybind $MOD-Shift-b spawn date_read
hc keybind $MOD-v spawn mpv-yt
hc keybind $MOD-r xsel | espeak
hc keybind $MOD-d spawn speedcrunch
hc keybind $MOD-m spawn mpd-menu

# focusing clients
hc keybind $MOD-h             focus left
hc keybind $MOD-n             focus down
hc keybind $MOD-e             focus up
hc keybind $MOD-i             focus right

# moving clients              
hc keybind $MOD-Shift-h       shift left
hc keybind $MOD-Shift-n       shift down
hc keybind $MOD-Shift-e       shift up
hc keybind $MOD-Shift-i       shift right

# splitting frames
hc keybind $MOD-y             split  right  0.5
hc keybind $MOD-l             split  bottom   0.5

# resizing frames
resizestep=0.05
hc keybind $MOD-Control-h      resize left +$resizestep
hc keybind $MOD-Control-n      resize down +$resizestep
hc keybind $MOD-Control-e      resize up +$resizestep
hc keybind $MOD-Control-i      resize right +$resizestep

# tags
tag_names=("1" "2" "3" "4" "5" "6" "7" "8" "9")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$MOD-$key" use_index "$i"
        hc keybind "$MOD-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $MOD-period use_index +1 --skip-visible
hc keybind $MOD-comma  use_index -1 --skip-visible

# layouting
hc keybind $MOD-Shift-g close_or_remove
hc keybind $MOD-f fullscreen toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $MOD-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical max grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $MOD-Button1 move
hc mousebind $MOD-Button2 zoom
hc mousebind $MOD-Button3 resize

# theme

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
#hc set frame_border_active_color '#C9CBFF'
#hc set frame_border_normal_color '#575268'
#hc set frame_bg_normal_color '#C9CBFF'
#hc set frame_bg_active_color '#575268'
hc set frame_border_active_color '#8FBCBB'
hc set frame_border_normal_color '#434C5E'
hc set frame_bg_normal_color '#8FBCBB'
hc set frame_bg_active_color '#434C5E'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

#hc attr theme.active.color '#C9CBFF'
#hc attr theme.normal.color '#575268'
hc attr theme.active.color '#8FBCBB'
hc attr theme.normal.color '#434C5E'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#F8BD96'
hc attr theme.active.outer_color '#F8BD96'
hc attr theme.background_color '#434C5E'
#hc attr theme.background_color '#575268'

hc set window_gap 0
hc set frame_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule title~"galculator" floating=true
hc rule title~"aseprite" floating=true
hc rule class~"SpeedCrunch" floating=true
hc rule class~"pinentry-qt5" floating=true
hc rule class~"winecfg.exe" floating=true

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
