#!/usr/bin/env bash

ACTIVE=false
pgrep -x go-timer > /dev/null && {
	ACTIVE=true
}

if $ACTIVE; then
	CHOICE=$(printf "=== $(cat /tmp/go-timer) ===\nStop Timer\nStopwatch\n-m 5\n-m 10\n-m 15\n-m 18" | dmenu)
else
	CHOICE=$(printf "=== Timer ===\nStop Timer\nStopwatch\n-m 5\n-m 10\n-m 15\n-m 18" | dmenu)
fi

echo $CHOICE
if [[ $CHOICE = "Stop Timer" ]]; then
	pkill go-timer	
elif [[ $CHOICE = "Stopwatch" ]]; then
	go-timer -stopwatch -timeFile
else
	go-timer -alarmFile ~/sync/bin/alarm.mp3 -timeFile $CHOICE
fi
