#!/bin/sh

pgrep proton-mail-bri > /dev/null 2> /dev/null && {
	echo "em: Proton mail bridge alredy runing."
	neomutt
	exit 0
}
echo "em: Starting proton mail bridge."
proton-mail-bridge > /dev/null 2> /dev/null &
sleep 15
neomutt
