#!/bin/sh

maim -s /tmp/image_copy_tmp.png
tesseract /tmp/image_copy_tmp.png /tmp/image_copy_tmp --dpi 150
cat /tmp/image_copy_tmp.txt | xclip -selection clip 
notify-send "Image Copy" "$(cat /tmp/image_copy_tmp.txt)"
rm /tmp/image_copy_tmp*
