#!/bin/sh

vpnstatus () {
    STAT=$(ip addr | grep proton | wc -l)
    if [ $STAT -eq 2 ]
    then
	echo "Connected"
    else
	echo "Disconneced"
    fi
}
ldate () {
    echo $(date +"%a %b %D %R:%S")
	# Tiawan Time.
    echo $(TZ=Asia/Taipei date +"%a %b %D %R:%S :TW")
}

ram () {
	free -h | grep Mem | awk '{ print $3"/"$2  }'
}
 
disk () {
	df -h -t btrfs | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
	df -h -t ext4 | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
	df -h -t fat32 | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
	df -h -t ntfs | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
}
kernal () {
	uname -r
}
timeup () {
	uptime -p | sed 's/up\ //g' | sed 's/\ //g' | sed 's/\,//g' | sed 's/days/D:/g' | sed 's/hours/H:/g' | sed 's/minutes/M/g'
}
cpu_usage () {
	top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
}

notify-send "No Bar" "$(ldate)
Vpn: $(vpnstatus)
Exip: $(curl -L ifconfig.me)
Cpu: $(cpu_usage)
Ram: $(ram)
Uptime: $(timeup)
Kernal: $(kernal)

---Disk Usage---
$(disk)"
