#!/bin/sh

vpnstatus () {
	vpnStatus.sh dunst
}
ldate () {
    echo $(date +"%a %b %y/%m/%d %R:%S")
	# Tiawan Time.
    echo "TW: "$(TZ=Asia/Taipei date +"%y/%m/%d %R:%S")
}

ram () {
	free -h | grep Mem | awk '{ print $3"/"$2  }'
}
 
disk () {
	df -h -t btrfs | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
	df -h -t ext4 | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
	df -h -t fat32 | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
	df -h -t ntfs | awk '{if (NR!=1) {print $6": " $3"/"$2" ("$5")"} }'
}
kernal () {
	uname -r
}
timeup () {
	uptime -p | sed 's/up\ //g' | sed 's/\ //g' | sed 's/\,//g' | sed 's/days/D:/g' | sed 's/hours/H:/g' | sed 's/minutes/M/g'
}
cpu_usage () {
	top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
}

lanip () {
	hostname -I | awk '{print  $1}'
}

exip () {
	curl -L ifconfig.me &
}

out () {
	echo "$(ldate)
Vpn: $(vpnstatus)
Ip: $(lanip) 
Exip: $(exip)
Cpu: $(cpu_usage)
Ram: $(ram)
Uptime: $(timeup)
Kernal: $(kernal)

<b>--- Disk Usage ---</b>
$(disk)
"
}

notify-send "No Bar" "$(out)"
