#!/usr/bin/env bash

# This is a fork of passmenu meaning this script is licenced under GPLV2 or latter.

shopt -s nullglob globstar
PREFIX=${PASSWORD_STORE_DIR-~/.password-store}
PASSWORD_FILES=( "$PREFIX"/**/*.gpg )
PASSWORD_FILES=( "${PASSWORD_FILES[@]#"$PREFIX"/}" )
PASSWORD_FILES=( "${PASSWORD_FILES[@]%.gpg}" )

# len_check (){
# 	i="${#PASSWORD_FILES[@]}"; ((--i))
# 	while [[ i > 0 ]]; do
# 		ITEM=${PASSWORD_FILES[$i]}
# 		echo $ITEM
# 		# if [[ ${#ITEM} > 30 ]]; then
# 		# 	{PASSWORD_FILES[$i]}=""
# 		# fi	
# 		((--i))
# 	done
# }; len_check

PASS=$(printf '%s\n' "${PASSWORD_FILES[@]}" | "dmenu" "$@")

[[ -n $PASS ]] || exit 

ACTION=$(printf "Copy Username\nCopy Password\nAuto Type\nCopy url\nShow Comments"| dmenu)

copy_pass (){
	pass show --clip=0 $PASS
}

copy_username (){
	pass show $PASS | grep 'login:' | sed 's/login:\ //' | xclip -selection clipbord
}

case $ACTION in
	'Copy Username') copy_username;;
	'Copy Password') copy_pass;;
	'Auto Type'){
		copy_username
		copy_username
		xdotool key ctrl+v
		xdotool key Tab
		copy_pass
		xdotool key ctrl+v
		xdotool key Return
	};;
	'Copy url') pass show $PASS | grep 'url:' | sed 's/url:\ //' | xclip -selection clipbord;;
	'Show Comments') pass show $PASS | grep 'comments:' | sed 's/comments:\ //'
esac
