#!/usr/bin/env bash
source $HOME/.zsource/isin

MENU=dmenu
IMAGEVIEWER=feh
IMAGEEDITOR=gimp
IMAGETMPNAME=/tmp/screen_shooter_tmp.png 
SAVEDIR=~
NOTEDIR="$HOME/Notes/Tid-bits"

MAIMIN=$(isin mmaim)
if [ $MAIMIN ]; then
	echo $(isin mmaim)
	maim -s $IMAGETMPNAME
else
	echo "screen_shooter: Maim is not found in \$PATH."
	exit 1
fi

choice (){
	CHOICE=$(printf "View\nEdit\nSave\nSave and Note\nCopy to Clipbord\nExit" | $MENU)
}
choice

KICKOUT=true
while $KICKOUT; do
	case $CHOICE in
	View)
		$IMAGEVIEWER $IMAGETMPNAME
		choice ;;
	Edit)
		$IMAGEEDITOR $IMAGETMPNAME
		choice ;;
	Save) 
		mv $IMAGETMPNAME $SAVEDIR/$(date -Iseconds).png 
		KICKOUT=false ;;
	"Save and Note")
		NOTENAME=$(printf "== Enter Name ==" | $MENU)
		NOTENAMESP=$NOTENAME # Saves $NOTENAME with spaces to $NOTENAMESP.
		NOTENAME=$(echo $NOTENAME | sed 's/ /_/g') # Replaces spaces ' ' in $NOTENAME with underscors '_'.
		IMAGENAME="$NOTEDIR/$(date -Iseconds)-$NOTENAME.png"
		mv $IMAGETMPNAME $IMAGENAME
		printf "#$NOTENAMESP\n\n![$NOTENAMESP]($IMAGENAME)" > "$NOTEDIR/$NOTENAME.md"
		printf "\n[$NOTENAMESP][$NOTENAME.md]" >> "$NOTEDIR/index.md" # Append index.md.
		case $(printf "Edit Note\nExit" | $MENU) in
			"Edit Note") alacritty -e $EDITOR "$NOTEDIR/$NOTENAME.md" ;;
			Exit) KICKOUT=false ;;
		esac ;;
	"Copy to Clipbord") 
		xclip -selection clipboard -t image/png -i $IMAGETMPNAME 
		KICKOUT=false ;;
	Exit) KICKOUT=false ;;
	esac
	
	# Closes prosses if usesr closes $MENU.
	if [ -n $(pgrep $MENU) ]; then
		KICKOUT=false
	fi
done

test -f $IMAGETMPNAME && rm $IMAGETMPNAME
