#!/bin/sh

alarm () {
	while true; do
		ffplay -f lavfi -i "sine=frequency=500:duration=1" -autoexit -nodisp
		ffplay -f lavfi -i "sine=frequency=1000:duration=1" -autoexit -nodisp
		ffplay -f lavfi -i "sine=frequency=1500:duration=1" -autoexit -nodisp
	done
}

echo "Timer set for $1"
sleep $1
notify-send "Timer Done."
alarm 
