#!/bin/bash

if [ $(echo $1 | grep http | wc -l) == 1 ];then
	if [ $(echo $1 | grep youtube.com | wc -l) == 1 ];then 
		mpv --fs $1
	elif [ $(echo $1 | grep lbry.tv | wc -l) == 1 ];then
		mpv --fs $1
	else
		$BROWSER $1 # This last one is a bit buggy and will not work if launched for sertent programs.
	fi
elif [ $(echo $1 | grep gemini:// | wc -l) == 1 ];then
	amfora $1
fi
