#!/usr/bin/env bash

selSER () {
  SER=$(ls -1 /etc/wireguard | fzf --height=10 --reverse | sed 's/\.conf//')
  if [[ $SER == '' ]]; then
    echo "Invaled server selected"
    exit 1
  fi
}

if [ $(whoami) != 'root' ]; then
	echo "!!!MUST BE RUN AS ROOT!!!"
else
	if [[ $(wg show) == '' ]]; then
		echo "Connecting"
    selSER
		wg-quick up $SER
    wg show > $HOME/.wg_show
	else
		echo -n "Alredy connected. (r)econnect or (d)issconnect? [r] "; read INPUT
		if [[ $INPUT == [Dd]* ]]; then
      echo "Disonnecting"
      wg-quick down $(wg show | grep "interface" | sed 's/interface: //')
		else
			echo "Reconnecting"
      selSER
      wg-quick down $(wg show | grep "interface" | sed 's/interface: //')
			wg-quick up $SER
      wg show > $HOME/.wg_show
		fi
	fi
fi
